# Generated by Django 5.1.5 on 2025-02-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowziApp', '0002_alter_likes_user'),
        ('userauths', '0002_profile_bio_profile_first_name_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_images',
            field=models.ManyToManyField(blank=True, related_name='saved_images', to='FlowziApp.post'),
        ),
    ]
