# Generated by Django 5.1.5 on 2025-03-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowziApp', '0002_alter_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Tag'),
        ),
    ]
