# Generated by Django 5.1.3 on 2026-04-24 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("directMessage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("date", "id")},
        ),
    ]
